### ISSUE TITLE
Jekyll plugin using the raml_parser to generate an API console

### ISSUE THREAD

**Issue by analytically** [ePages-de/raml_parser#14]
Will this be open sourced as well? Would be awesome!

**Comment by choffmeister** [comment]
Indeed it already is. Not as individual project but as part of our documentation repository: We are using it here:

https://github.com/ePages-de/epages-docs/blob/develop/_plugins/raml.rb

The source code in the repository is licensed under MIT, so feel free to use it for whatever you like :)
