### ISSUE TITLE
Add this project to official RAML homepage

### ISSUE THREAD

**Issue by choffmeister** [ePages-de/raml_parser#3]
Send an email to `info@raml.org` to make this library visible on the official RAML project page at http://raml.org/projects.html.

**Comment by choffmeister** [comment]
@netzfisch Is it wished-for to have this Gem be announced at the RAML homepage? Shall I write them a mail?

**Comment by netzfisch** [comment]
sure :+1:

**Comment by choffmeister** [comment]
Sent a mail to the RAML guys. Waiting for response.

**Comment by sichvoge** [comment]
You should have an email.

**Comment by sichvoge** [comment]
Any progress on this project?

**Comment by choffmeister** [comment]
Sadly there is currently no progress here since the supported feature set is sufficient for our use.

But I can finally close the issue. Totally forgot about that.

**Comment by sichvoge** [comment]
Also no plans to update for RAML 1.0 I assume?
