### ISSUE TITLE
Publish to rubygems.org

### ISSUE THREAD

**Issue by choffmeister** [ePages-de/raml_parser#5]
See http://guides.rubygems.org/publishing/

**Comment by choffmeister** [comment]
@netzfisch Is it wished-for to have this gem published to the official repository of RubyGems?

**Comment by netzfisch** [comment]
sure :+1:

**Comment by choffmeister** [comment]
Great. Is there an epages rubygems account? If not, should I create one or just create a private one for pushing the gem?

**Comment by netzfisch** [comment]
gucke mal wie das andere, z.B. shopify handhaben, h?

Von: Christian Hoffmeister <notifications@github.com<mailto:notifications@github.com>>
Antworten an: ePages-de/raml_parser <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Monday 16 February 2015 15:58
An: ePages-de/raml_parser <raml_parser@noreply.github.com<mailto:raml_parser@noreply.github.com>>
Cc: Harm Behrens <h.behrens@epages.com<mailto:h.behrens@epages.com>>
Betreff: Re: [raml_parser] Publish to rubygems.org (#5)

Great. Is there an epages rubygems account? If not, should I create one or just create a private one for pushing the gem?

�

**Comment by choffmeister** [comment]
Soweit ich das sehe (z.B. bei https://rubygems.org/gems/liquid) gibt es gar keine organisationsgebundenen Accounts, sondern 1 bis n Besitzer die Pushrechte haben. Also erstelle ich mir einen eigenen Account.

**Comment by netzfisch** [comment]
ok, h)

Von: Christian Hoffmeister <notifications@github.com<mailto:notifications@github.com>>
Antworten an: ePages-de/raml_parser <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Monday 16 February 2015 17:47
An: ePages-de/raml_parser <raml_parser@noreply.github.com<mailto:raml_parser@noreply.github.com>>
Cc: Harm Behrens <h.behrens@epages.com<mailto:h.behrens@epages.com>>
Betreff: Re: [raml_parser] Publish to rubygems.org (#5)

Soweit ich das sehe (z.B. bei https://rubygems.org/gems/liquid) gibt es gar keine organisationsgebundenen Accounts, sondern 1 bis n Besitzer die Pushrechte haben. Also erstelle ich mir einen eigenen Account.

�

**Comment by choffmeister** [comment]
Gone live at https://rubygems.org/gems/raml_parser

![Ruby](http://media.giphy.com/media/yyRn2N7VVI5Q4/giphy.gif)
